title: "Steve's Pages"
description: "A place to learn, grow, and share support — tech, prompts, peer coaching"
url: "https://shodan2007.github.io"
baseurl: "/steves-pages"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

author:
  name: "Stef"
  avatar: "/assets/images/avatar.jpg"
  bio: "Technologist, peer coach, and prompt tinkerer. Building clarity through code and care."
  location: "Indianapolis, IN"
  email: "your-email@example.com"

social:
  type:  "Person"
  name:  "Stef"
  links:
    - "https://github.com/shodan2007"
    - "https://linkedin.com/in/porter-steve"

# Navigation links (sidebar or header)
navigation:
  - title: "Home"
    url: "/"
  - title: "Demos"
    url: "/demos/"
  - title: "AI Prompts"
    url: "/ai/"
  - title: "Blog"
    url: "/blog/"
  - title: "Tags"
    url: "/tags/"

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Steve"
      read_time: true
      comments: false
      share: true
      related: true

# Include custom pages folder
include:
  - _pages

# Exclude build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

