title: "Steve's Pages"
description: "A place to learn, grow, and share support"
url: "https://shodan2007.github.io"
baseurl: "/steves-pages"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
paginate: 5
