

title: "Steve's Pages"
description: "A place to learn, grow, and share support — tech, prompts, peer coaching"
url: "https://shodan2007.github.io"
baseurl: "/steves-pages"

remote_theme: mmistakes/minimal-mistakes
# minimal_mistakes_skin: "default"
header:
  nav: main

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Add this if it's missing:
include:
  - assets/css

author:
  name: "Steve"
  avatar: "/assets/images/avatar.png"
  bio: "Technologist, peer coach, and prompt tinkerer. Building clarity through code and care."
  location: "Indianapolis, IN"
  email: "shodan2007@gmail.com"

social:
  type:  "Person"
  name:  "Steve"
  links:
    - "https://github.com/shodan2007"
    - "https://linkedin.com/in/porter-steve"

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: ""
    values:
      author: "Steve"
      read_time: false
      comments: false
      share: false
      related: false

# Enable grid layout for posts
paginate: 6
paginate_path: /page:num/

# Include custom pages folder
include:
  - _pages

# Exclude build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

